### ISSUE TITLE
fix bug of showing all traits to edit when starting game by pressing enter

### ISSUE THREAD

**Issue by zookae** [efruchter/Trait#9]
If you press enter (rather than clicking the "go" button on the other panel) the game will open up all traits for the player to edit after completing one wave. It also does not despawn the side editing pane while the game runs.

**Comment by efruchter** [comment]
Pushed fix to master in commit:
https://github.com/efruchter/Trait/commit/82f10e2d19f495e2514f595b5af39ae69d2422c6

**Comment by efruchter** [comment]
Also, to make issue tracking easier, I'll let you close down the issue if the commit fixed your problem.
